cmake_minimum_required(VERSION 3.20)
project(InvestEdge LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(CURL REQUIRED)
find_package(Threads REQUIRED)
include(FetchContent)
FetchContent_Declare(json URL https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz)
FetchContent_MakeAvailable(json)
add_executable(profit_loss profit_loss.cpp mains/profit_loss_main.cpp)
add_executable(portfolio_analyzer portfolio_analyzer.cpp mains/portfolio_analyzer.cpp)
add_executable(real_time_tracker real_time_tracker.cpp mains/real_time_tracker_main.cpp)
add_executable(stock_news stock_news.cpp mains/stock_news_main.cpp)
add_executable(risk_management risk_management.cpp mains/risk_management.cpp)
foreach(target real_time_tracker stock_news risk_management)
  target_link_libraries(${target} PRIVATE CURL::libcurl nlohmann_json::nlohmann_json Threads::Threads)
endforeach()
